name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repo
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instala dependencias
        run: npm install

      - name: Construye el proyecto
        run: npm run build

     
      - name: Despliega a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseToken: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live

